spring:
  application:
    name: SBJpaQueryApproach
  datasource:
    url: jdbc:mysql://localhost:3306/revesiondb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
